### ISSUE TITLE
directus_shares missing type in graphql

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#10694]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When querying anything using graphql with v9.4.0 i only get the response

```
{
  "errors": [
    {
      "message": "TypeError[directus_shares.collection]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": null
}
``` 

This happened after i upgraded from v9.3.0. I tried researching it a bit, but sadly couldn't figure out anything 😓  I have a sneaking suspicion that it is related to the the database field being called "collection", but i might be very wrong

### To Reproduce

I haven't tried to reproduce it in a clean environment, so it might be specific to my setup. I don't have the time to debug it thoroughly atm, but i will look into it further if it cannot be reproduced by anyone else.
If necessary i can create a database dump and send :)

### Errors Shown

I get this in the application log

```
2021-12-26T11:27:58.364349356Z Error: TypeError[directus_shares.collection]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })
2021-12-26T11:27:58.364355557Z     at TypeMapper.convertOutputFieldConfig (/directus/node_modules/graphql-compose/lib/TypeMapper.js:230:27)
2021-12-26T11:27:58.364359857Z     at ObjectTypeComposer.setField (/directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:162:46)
2021-12-26T11:27:58.364381757Z     at /directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:168:18
2021-12-26T11:27:58.364386057Z     at Array.forEach (<anonymous>)
2021-12-26T11:27:58.364390957Z     at ObjectTypeComposer.addFields (/directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:167:32)
2021-12-26T11:27:58.364395357Z     at getTypes (/directus/node_modules/directus/dist/services/graphql.js:337:105)
2021-12-26T11:27:58.364399757Z     at getReadableTypes (/directus/node_modules/directus/dist/services/graphql.js:396:62)
2021-12-26T11:27:58.364403857Z     at GraphQLService.getSchema (/directus/node_modules/directus/dist/services/graphql.js:134:41)
2021-12-26T11:27:58.364408057Z     at GraphQLService.execute (/directus/node_modules/directus/dist/services/graphql.js:91:29)
2021-12-26T11:27:58.364412157Z     at /directus/node_modules/directus/dist/controllers/graphql.js:27:40

```

### What version of Directus are you using?

9.4.0

### What version of Node.js are you using?

16.0 (the docker version i guess)

### What database are you using?

Mysql 8.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker (through Azure)

**Comment by TheAzack9** [comment]
Just found this: https://github.com/directus/directus/pull/10674

So i presume this is fixed in the next version :) Just close if that is the case

**Comment by TheAzack9** [comment]
Or actually, i'm pretty certain so i'll just close it myself ;)

**Comment by signalwerk** [comment]
@TheAzack9 thank you for this issue. with it I found the MR. let's hope v9.4.1 will include it.

**Comment by signalwerk** [comment]
@TheAzack9 
btw: mabe you could reopen the bug, since it's not in the release yet and people will notice it.

**Comment by cdiaz** [comment]
I am using [9.4.1](https://github.com/directus/directus/releases/tag/v9.4.1) in a new project and I have this problem when trying to use Graphql.
 #[10674](https://github.com/directus/directus/pull/10674) was merged in this release, but the problem persists for me

**Comment by TheAzack9** [comment]
9.4.1 solved my issues using the `/graphql` endpoint at least 😅 Might it be something else? 
@cdiaz I would recommend opening another issue if you still have problems with details of your environment. 😊 The devs are always quick to respond and amazing at finding issues!
