### ISSUE TITLE
One to Many, Remove Button missing

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1172]
To help us resolve your issue more quickly, please use the following template:

For feature requests please chat with us through [getdirectus.com](http://getdirectus.com).

## Version Info
  - Directus version: d2128abec

## Expected Behavior

I have created a one-to-many field to manage child records. In my case the parent is a hotel, the children are the offers.

In the field's settings I have enabled the "Remove Button". So I expect I would be able to remove the offers belonging to one hotel when editing that hotel. 

## Actual Behavior

I can not see any button for removing offers while editing an hotel.

## Logs or Screenshots

Field settings:

![bildschirmfoto 2016-06-19 um 00 36 58](https://cloud.githubusercontent.com/assets/26493/16174143/5912f340-35b6-11e6-9f52-1e44350ded08.png)

![bildschirmfoto 2016-06-19 um 00 37 03](https://cloud.githubusercontent.com/assets/26493/16174144/5a9e939a-35b6-11e6-943e-592e19d4b5ae.png)

No remove button:

![bildschirmfoto 2016-06-19 um 00 36 37](https://cloud.githubusercontent.com/assets/26493/16174141/566eabca-35b6-11e6-8d6f-7e3cfd99edc8.png)

**Comment by benhaynes** [comment]
@laszlokorte Did you hover over the options in that UI? The "X" appears at the far-right on hover of the item row. If you're not seeing it this is definitely a bug.

If you ARE seeing it then we might need to look at the UI to make sure it's intuitive enough how to delete.

Let us know!

**Comment by laszlokorte** [comment]
I am not seeing it. It also not in the markup (devtools).

I just noticed that I am not seeing a delete button in global list views of the tables either.

**Comment by benhaynes** [comment]
Hey @laszlokorte – so I've added a O2M through Directus (dev branch) and it seems to be working for me. With multiple/many fields it does get pushed far to the right (off screen for smaller viewports) – but I can see it when I expand the browser... so it should still be in dev tools.

Maybe give it a try on the dev branch (master should also work since we just merged). Maybe this was resolved with our big push last week.

![screen shot 2016-07-12 at 10 59 35 am](https://cloud.githubusercontent.com/assets/522079/16771864/0bf6f094-4820-11e6-9927-ecd64cd79cbc.png)

![screen shot 2016-07-12 at 10 59 46 am](https://cloud.githubusercontent.com/assets/522079/16771870/102e66d8-4820-11e6-853d-278939e5a06a.png)

![screen shot 2016-07-12 at 11 02 40 am](https://cloud.githubusercontent.com/assets/522079/16771918/3618d9dc-4820-11e6-8b7f-e23247cbb3b3.png)

**Comment by benhaynes** [comment]
> I just noticed that I am not seeing a delete button in global list views of the tables either.

Do you mean for the Item listing page? This page doesn't have a delete button, it uses the status feature (clicking on the left check boxes for items). Also, this feature works when a status field is included (default: `active`) or you have permission for a hard delete on that table.

Let me know if this helps!

**Comment by benhaynes** [comment]
Hey @laszlokorte – we're consistently seeing the remove button over here... let us know if you have time to test again on your side. If the problem persists we'll re-open this, but for now it seems to not be an issue.

Based on the UI design in the screenshots you might have had an outdated version... but it's hard to say if that was the cause.

**Comment by laszlokorte** [comment]
I just did a fresh install of the master branch. I am still not seeing a delete button in the OTM field table.

It's a completely fresh install and I created all my table just through the directus UI.

![bildschirmfoto 2016-08-03 um 03 14 37](https://cloud.githubusercontent.com/assets/26493/17350651/d2cb81f8-5928-11e6-8313-d78fdb10f462.png)

**Comment by laszlokorte** [comment]
Now I tracked down the error: I set the foreign key column of the child table to NOT NULL.
So this check is returning false:
https://github.com/directus/directus/blob/master/app/core-ui/one_to_many.js#L178

But I do not understand why that check is there in the first place. I would expect the child record to be just deleted and not to set it's parent_id column to NULL.

**Comment by benhaynes** [comment]
Interesting – there may have been a time before the status column when soft-delete was accomplished by unassigning the `id` so that the item was available as a choice with other OTM fields. 

Either way, we need to decide how to handle this by default and what UI options we'll support.

* Delete Item (hard delete) – Gone... forever
* NULL ID (soft delete) – Goes back into the pool of choices
* Use status column (soft delete) – Is still related to that item, but is inactive (not in pool)

For now, it seems that we want to clarify (docs and code) the `allow null` issue with this UI. Then we could base it on the schema/permissions:

* **Permission = Hard**: Delete Item
* **Permission = Soft & No Status**: NULL ID
* **Permission = Soft & Status**: Inactive

What do you think @laszlokorte and @WellingGuzman ?

**Comment by laszlokorte** [comment]
@benhaynes sounds good to me. 

But: 
> NULL ID (soft delete) – Goes back into the pool of choices

As far as I can see the OTM field does currently not provide a way to *add some existing child record by assigning it's parent_id*.

**Comment by benhaynes** [comment]
Ahh, then that is a mistake. All of the relational UIs should have a way to choose from the existing items. This specific UI should also have an option to choose from: null only, or any items (would reassign). 

Are you familiar with the UI options enough to try adding that "Choose" option (and have time/interest 😉), or should I add this to FeatHub?

**Comment by laszlokorte** [comment]
Better add it to FeadHub. I do not have that much time currently.

**Comment by benhaynes** [comment]
Not a problem! [Added to FeattHub](http://feathub.com/directus/directus/+60)

**Comment by WellingGuzman** [comment]
> Permission = Soft & No Status: NULL ID

The issue there still the same if the column doesn't allow NULL.

**Permission** = **Hard**: Delete Item
_**Permission** = **Soft & No Null**: Can't delete Item_
**Permission** = **Soft & Null & No Status**: NULL ID
**Permission** = **Soft & Status**: Inactive

What do you think?

**Comment by benhaynes** [comment]
This makes sense... but the second option never needs to happen. No one chooses "soft delete"... it is soft-delete **if** there is no `status` column. So the second option above would never happen.

Other than that... this looks good!

**Comment by benhaynes** [comment]
@WellingGuzman after testing this, if the FK ALLOWS NULL and you have a status column, it should only adjust it to NULL (it should NOT also change the status). Or we need to at least set a UI option for this.

Right now, I am testing careers being assigned to offices... and when you remove the relationship it deletes the item from Directus (active = 0) and you can't reassign it or see it at all.

_Changing the first one..._
```
HAS STATUS COLUMN AND ALLOW NULL
  status = **DO NOT CHANGE**, column = NULL


HAS STATUS COLUMN AND NOT ALLOW NULL
  status = 0, column = ID


NO STATUS COLUMN AND ALLOW NULL
  remove status, column = NULL

  
NO STATUS COLUMN AND NOT ALLOW NULL
  DELETE ROW
```

**Comment by WellingGuzman** [comment]
@benhaynes this should do the fix: https://github.com/directus/directus/commit/93fe685a9f11cce7a9dd38d52bfd22233c989b92

**Comment by benhaynes** [comment]
This is working great now! Thanks W
