### ISSUE TITLE
Flows: Unable to use `{{$last.body.keys}}` in a read data Operation

### ISSUE THREAD

**Issue by vanling** [directus/directus#13787]
### Describe the Bug

When trying to pass on multiple keys to an read/update operation the keys are parsed as 
```
"key": [
    "[\"03389a8b-4309-498a-b65b-9d0853d8881b\",\"60cbaa7c-de55-4154-981f-c993df1633be\",\"ba3cabf9-570e-4039-8707-2b80b3d44005\"]"
  ]
  ```
  
  I expected to get the following 
  ```
  "key": [
    "03389a8b-4309-498a-b65b-9d0853d8881b",
    "60cbaa7c-de55-4154-981f-c993df1633be",
    "ba3cabf9-570e-4039-8707-2b80b3d44005"
  ]
  ```
  and continue in the flow with the selected id/values

### To Reproduce

1. Create a `manual trigger`
2. follow up with a `read data`
3. Add `{{$last.body.keys}}` as ID's

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

v16.15.1

### What database are you using?

 mysql-server-8.0

### What browser are you using?

Edge

### How are you deploying Directus?

npm install on ubuntu server

### Images

<img width="691" alt="Schermafbeelding 2022-06-08 om 19 26 32" src="https://user-images.githubusercontent.com/50699657/172681205-5597f6e2-5e43-4975-8c42-01c643b39cda.png">
<img width="825" alt="Schermafbeelding 2022-06-08 om 19 27 19" src="https://user-images.githubusercontent.com/50699657/172681210-f3d03613-b41b-46f6-93f5-8414111e9fd3.png">
<img width="828" alt="Schermafbeelding 2022-06-08 om 19 28 12" src="https://user-images.githubusercontent.com/50699657/172681212-eb875c1d-b424-4555-8495-977f56d9bb1a.png">

**Comment by massimans** [comment]
Hi,
you can work around it by using the raw editor and puting {{$last.body.keys}} but it will break the IDs as of directus 9.12.2
ps: i don't think it's api related since the issue appears to be that the field is adding [ ] arround {{$last.body.keys}}

**Comment by luciandavidescu** [comment]
Is this fixed really or am I missing something? I get the exact same issue in 9.22.4, even with the raw code editor.
![log](https://user-images.githubusercontent.com/26859276/214165432-962e8f92-eaf6-4ee0-8012-313093cc6b3e.jpg)
![code](https://user-images.githubusercontent.com/26859276/214165439-88efe29b-60b4-4dc1-85f6-89e13bd5c2b9.jpg)

**Comment by rijkvanzanten** [comment]
I believe the raw value is without quotation marks

**Comment by luciandavidescu** [comment]
They seem mandatory, can't save if I try to take them out
![quo](https://user-images.githubusercontent.com/26859276/214170742-faf73c1e-00d8-4d60-947a-897d23d4a011.jpg)

**Comment by luciandavidescu** [comment]
Weirdly enough, if I add a "run script" block and simply redefine the array as itself, it then works.
![exec](https://user-images.githubusercontent.com/26859276/214174214-ef3e71bb-821f-490b-b420-a7d553a3080b.jpg)
*"{{exec.related}}"

**Comment by EnzoBitMatrix** [comment]
How was this fixed?
I have the EXACT same problem that @luciandavidescu does above...

If I put the variable into a script, it shows without slashes, when I put it in a Create Flow, it adds them, and therefor makes the UUID invalid...

![image](https://user-images.githubusercontent.com/22970783/225491727-6d875566-889e-4ff2-9150-b1b0f53a9e5a.png)

![image](https://user-images.githubusercontent.com/22970783/225491600-7b1135cd-a4f5-40aa-8853-a7e9f965c2e3.png)

It say's this was fixed, but I can't find the fix.

**Comment by bogdan-nita** [comment]
Same issue is still present. It would be nice to be able to read items with the `keys` field of the $trigger on items.create / items.update but the Read Data operation doesn't play well with an array of strings instead of an array of numbers. When converting the array of string to numbers through a script operation I get the double square brackets issue.

**Comment by nhadsall** [comment]
I don't see any way around this. There should be an option to ignore the json validator when it's wrong.
