### ISSUE TITLE
OpenID integration with Authentik failing - RPError [OpenID] Unknown RP error 

### ISSUE THREAD

**Issue by jradikk** [directus/directus#15888]
### Describe the Bug

I have a Docker installation of Directus and I'm trying to enable SSO using OpenID integration with Authentik. Unfortunately, after a successful redirection to Directus callback URL, I receive INVALID_CREDENTIALS error. The following can be seen in the logs:

```
directus-directus-1  | 14:38:45 🔍 RPError [OpenID] Unknown RP error
directus-directus-1  | 14:38:45 ⚠️  Invalid user credentials.
directus-directus-1  | 14:38:45 ✨ request completed GET 302 /auth/login/authentik/callback?code=040ce81e53cb46f4a7b617c0e5f8c1fd&state=8iT8BITBTkQpxacPMDvxNgINmgartvkUFQ-vll3BuWc 550ms
directus-directus-1  | 14:38:45 ✨ request completed GET 304 /admin/login?reason=INVALID_CREDENTIALS 5ms
.....
directus-directus-1  | 14:38:46 🐛 "refresh_token" is required in either the JSON payload or Cookie
```
Directus config related to OpenID:
```
      - AUTH_PROVIDERS=authentik
      - AUTH_AUTHENTIK_DRIVER="openid"
      - AUTH_AUTHENTIK_CLIENT_ID="somesecretstring"
      - AUTH_AUTHENTIK_CLIENT_SECRET="somelongersecretstring"
      - AUTH_AUTHENTIK_ISSUER_URL="https:/authentik.domain/application/o/directus/.well-known/openid-configuration"
      - AUTH_AUTHENTIK_IDENTIFIER_KEY="email"
      - AUTH_AUTHENTIK_ICON="https://directus.io/assets/og-image.png"
      - AUTH_AUTHENTIK_ALLOW_PUBLIC_REGISTRATION="true"
      - AUTH_AUTHENTIK_DEFAULT_ROLE_ID="5eae2a9c-07e1-48b0-b680-04275c9bccf8"
```

I've tried changing virtually any possible configuration at Authentik side without any success. 

What's, I believe, important is that the same openid integration with auth0 works perfectly. And my other apps also successfully connect to Authentik. The problem is only with Directus 

### To Reproduce

1. Spin up authentik
2. Create provider with the following configuration
<img width="981" alt="Screenshot 2022-10-05 at 17 48 47" src="https://user-images.githubusercontent.com/8902554/194091002-27fb149a-0915-4330-a341-fc47979177be.png">
<img width="1080" alt="Screenshot 2022-10-05 at 17 47 28" src="https://user-images.githubusercontent.com/8902554/194091006-0dbdbf5a-2994-4659-94f3-7576fa318ef3.png">
3. Connect directus to it using environment variables mentioned above
4. Login using Authentik Provider

### Errors Shown

```
directus-directus-1  | 14:38:45 🔍 RPError [OpenID] Unknown RP error
directus-directus-1  | 14:38:45 ⚠️  Invalid user credentials.
directus-directus-1  | 14:38:45 ✨ request completed GET 302 /auth/login/authentik/callback?code=040ce81e53cb46f4a7b617c0e5f8c1fd&state=8iT8BITBTkQpxacPMDvxNgINmgartvkUFQ-vll3BuWc 550ms
directus-directus-1  | 14:38:45 ✨ request completed GET 304 /admin/login?reason=INVALID_CREDENTIALS 5ms
.....
directus-directus-1  | 14:38:46 🐛 "refresh_token" is required in either the JSON payload or Cookie
```

### What version of Directus are you using?

9.6, 9.17.4, 9.18.1

### What version of Node.js are you using?

v16.17.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome, Safari

### How are you deploying Directus?

Running locally in Docker and in Kubernetes as a deployment

**Comment by jradikk** [comment]
Eventually we figured out that this was the authentik issue. 
https://github.com/goauthentik/authentik/issues/3739

**Comment by Fma965** [comment]
I'm literally actively trying to do this, good to know thanks.

**Comment by dorianim** [comment]
@jradikk how did you get this to work? I have the same issue, but it should be fixed in Authentik `2022.10.1`, or not?

**Comment by Fma965** [comment]
It works on latest version :)

**Comment by dorianim** [comment]
did you change anything about the config you posted above? I just can't get it to work

**Comment by Fma965** [comment]
I'm not the OP

**Comment by Dan6erbond** [comment]
I'm still getting this issue with Authentik v2023.6.0. Is there any specific configuration that ensures refresh tokens are included in the payload?

**Comment by darv278** [comment]
For those who are still trying to enable single sign-on via Authnetik

It was possible to enable authorization through Authentik (version 2023.8.3) only when the certificate was enabled in the provider section.
![image](https://github.com/directus/directus/assets/108269014/735e0dd2-22ef-420a-8343-1f65bc9724a3)

Directus environment file:
`AUTH_PROVIDERS="authentik"
AUTH_AUTHENTIK_DRIVER:="openid"
AUTH_AUTHENTIK_CLIENT_ID="client-id-authentik"
AUTH_AUTHENTIK_CLIENT_SECRET="client-secret-authentik"
AUTH_AUTHENTIK_ISSUER_URL="https://authentik.domain.com/application/o/directus/"
AUTH_AUTHENTIK_IDENTIFIER_KEY="email"
AUTH_AUTHENTIK_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_AUTHENTIK_DEFAULT_ROLE_ID="role-id-directus"
`
