### ISSUE TITLE
Apply snapshot generated on SQLite3 into PostgreSQL (UUID Type)

### ISSUE THREAD

**Issue by GustavoBlaze** [directus/directus#17385]
### Describe the Bug

When your application has UUID column the Directus creates it as char(36) on SQLite and it works well! But when there are more collections with relationship between fields with UUID and you try to apply the snapshot in the PostgreSQL, it fails. The snapshot is not applied because it can't create the relationship.

However, i found something strange inside the snapshot. The UUID column of those collections should have type `uuid` and they were `string`. And changing it to `uuid` the snapshot started working fine!

![image](https://user-images.githubusercontent.com/25311644/216464170-d78894d3-f08d-4090-b6d7-9a26ab9d734f.png)

Unfortunally, i had this issue days ago i don't have that snapshot anymore and can't provide more informations about the error.

### To Reproduce

With a SQLite3 database, create collections with UUID as primary key and make relationship between them and then export the snapshot.

Try to apply this snapshot on a directus with postgres and it's going to fail!

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

18

### What database are you using?

Don't remember

### What browser are you using?

Not relevant

### How are you deploying Directus?

locally

**Comment by paescuj** [comment]
We haven't been able to reproduce this with the latest version (v9.22.4) and based on the given information, it seems like this issue has been fixed in the meantime. I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by azta** [comment]
I'm trying to migrate from sqlite to Postgres and I've encountered the same.

#12723 only looks for char(36), not varchar(36). My keys are mixed somehow. Maybe because I knew the client id was a uuid I was specific and a varchar(36) was the first thing I found?

```sql
CREATE TABLE IF NOT EXISTS "allotments"(
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
);
CREATE TABLE IF NOT EXISTS "allotments_clients"(
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `allotments_id` integer NULL,
  `clients_id` char(36) NULL,
);
CREATE TABLE IF NOT EXISTS "clients"(
  `id` char(36) NOT NULL,
  PRIMARY KEY(`id`),
);
CREATE TABLE IF NOT EXISTS "subscriptions"(
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
);
CREATE TABLE IF NOT EXISTS "purchases"(
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `client` varchar(36) NOT NULL DEFAULT null,
  `subscriptions` integer NOT NULL,
);
```

The purchases table has a varchar(36) for the client UUID. Not a char(36).

The data model works and we are using it I've not touched a line of code.

**Comment by paescuj** [comment]
@azrikahar Do you agree with me that it would indeed make sense and should be safe & pretty straightforward to include `varchar(36)` in the check from #12723 as well?

**Comment by GustavoBlaze** [comment]
> @azrikahar Do you agree with me that it would indeed make sense and should be safe & pretty straightforward to include `varchar(36)` in the check from #12723 as well?

i also noticed this on my snapshot one time, but it wasn't affecting me at all. However, i would recommend to take a look at the field type and write `uuid` into the snapshot instead of `string`. Just double check this, i know you guys weren't able to reproduce it, but i think it wasn't solved.

**Comment by azrikahar** [comment]
> @azrikahar Do you agree with me that it would indeed make sense and should be safe & pretty straightforward to include `varchar(36)` in the check from #12723 as well?

@paescuj Agreed! Coincidentally I recall there was a prior internal discussion with Wryn a while ago regarding this exact inclusion but it wasn't tracked at the time. Submitted PR #17615 for this 👍

**Comment by azta** [comment]
#17615 would have saved me a lot of time with my specific snapshot problem @azrikahar but do you think it may be better to go further?

```sql
CREATE TABLE test_uuids(
    uuid_a CHARACTER(36), 
    uuid_b CHAR(36), 
    uuid_c VARCHAR(36), 
    uuid_d NCHAR(36), 
    uuid_e FOOCHAR(36), 
    uuid_f SOMETHINGELSECHAR(36));

INSERT INTO test_uuids VALUES ('5EA82C62-07E9-4A8A-AAF5-20A199651D06', 
    '5EA82C62-07E9-4A8A-AAF5-20A199651D06', 
    '5EA82C62-07E9-4A8A-AAF5-20A199651D06', 
    '5EA82C62-07E9-4A8A-AAF5-20A199651D06', 
    '5EA82C62-07E9-4A8A-AAF5-20A199651D06', 
    '5EA82C62-07E9-4A8A-AAF5-20A199651D06');

```

Because of the way SQLite determines the column affinity (https://www.sqlite.org/datatype3.html#determination_of_column_affinity) all are `typeof()` text and can store uuids.

Instead of `char(36)` or `varchar(36)` maybe a regular expression would be more appropriate. SQLite does this:

https://github.com/sqlite/sqlite/blob/2d7829057e3806e232f12b66169158fd8f090266/src/build.c#L1655

**Comment by azrikahar** [comment]
@azta great question! I think that's a very valid concern, but upon further inspection, I was not able to reproduce `type: string` when snapshotting with `9.22.4` using an Image field that has a relationship to `directus_files` (that is using UUID as it's PK). By `type: string`, I'm pointing at a generated schema snapshot:

(this is only a part of the snapshot, to make things shorter in this discussion)

```yaml
# this is a part of a snapshot generated in 9.22.4

fields:
  - collection: a
    field: image
    type: uuid # this used to be snapshotted as "string"
    meta:
      collection: a
      conditions: null
      display: null
      display_options: null
      field: image
      group: null
      hidden: false
      interface: file-image
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special:
        - file
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: image
      table: a
      data_type: char # this used to be snapshotted as "varchar" in older versions
      default_value: null
      max_length: 36
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_files
      foreign_key_column: id
```

and if I were to swap `data_type: char` to `data_type: varchar` and keep `type: uuid` intact, it seems to still work without #17615. 🤔

As for the case of possible data_type, a regex would indeed be technically more exhaustive, but I believe any type that are not listed here will also not be recognized by Directus:

https://github.com/directus/directus/blob/fb41eee1edc2590a7732427a0051668e301c8cb3/api/src/utils/get-local-type.ts#L3-L103

so the general "support for more types of UUID in sqlite" might have to be a separate thing to tackle outside of the current context of applying schema snapshots.
