### ISSUE TITLE
Inability to assign roles to users

### ISSUE THREAD

**Issue by christiaangoossens** [directus/directus#2211]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
Directus version and branch (Or commit hash): 7.01 release zip from Github
PHP version: 7.2
MySQL version: 10.1
Web server: (Ex. Apache, nginx or IIS?) Apache
OS name and version: CentOS

## Expected Behavior

Ability to assign roles to users in any way

## Actual Behavior

Cannot find any way to assign users a role. There is no selection box on the user creation screen, nor in the screens for the Roles. I also get a server error if I search for anything with the roles filter:

![image](https://user-images.githubusercontent.com/9487666/47047164-2a9d0300-d197-11e8-87dc-7108fa13008c.png)

The same occurs when logging in with a new user after creation, with Directus giving a similar Server Error.

## Steps to Reproduce
 1. Use the schema.sql provided in the release zip
 2. Create user
 3. Use filter or login

**Comment by christiaangoossens** [comment]
Another issue, this time a lot more serious. Is this an issue with the schema file? How did this breaking bug get through the Release Candidates?

**Comment by rijkvanzanten** [comment]
> Is this an issue with the schema file?

We ran into this issue right when we launched 7 :/

Should be fixed in 7.0.1 though. Could you confirm with a fresh install?

> How did this breaking bug get through the Release Candidates?

Cause we have a tiny team working on it and people don’t really bother testing out RCs unfortunately.. 

_Hoe hard ik ‘t ook probeer, ik kan niet alles in m’n eentje 👉🏻👈🏻_

**Comment by christiaangoossens** [comment]
I started with the 7.0.1 zip, not having used any of the rc's, because I want to use this in semi-production, where I wanted something a bit more stable.

_Als ik er tijd voor over had dan zou ik je sowieso hebben geholpen :pensive:_

**Comment by christiaangoossens** [comment]
But the question remains: how do you assign users roles, if not through the MySQL tables directly?

**Comment by rijkvanzanten** [comment]
There's an interface on the user's detail page that allows you to set the user's role

**Comment by Mu9tafa-Online** [comment]
I can confirm that I can't find the inteface you mentioned guys, i did a fresh installation .. still unable to set roles.. may be you commit changes after 2.0.1 was released?! @benhaynes It would be great if you provide a screen shot of the new option enabled in your installation.

**Comment by benhaynes** [comment]
I just did a fresh install from the combined build version (7.0.1) and I do get the Roles interface (albeit in the wrong spot):

![screen shot 2018-10-17 at 2 39 54 pm](https://user-images.githubusercontent.com/522079/47109444-3ed71380-d21c-11e8-9fbe-6fce6b804e12.png)

**Comment by Mu9tafa-Online** [comment]
@benhaynes .. This is how my "Admin CP" looks like (It's different form yours ) I don't know why!
.
![drx](https://user-images.githubusercontent.com/5323832/47135745-cc187780-d2b1-11e8-88e6-59106a3d42df.png)

**Comment by Mu9tafa-Online** [comment]
also there is a gap between the number of requested CSS Files
.
This is on my **local environment**
========================
![drx_local](https://user-images.githubusercontent.com/5323832/47137036-c02eb480-d2b5-11e8-8adf-4f191d3b9824.png)


and below the "Directus Online Demo"
================================
![drx_demo](https://user-images.githubusercontent.com/5323832/47136959-8b226200-d2b5-11e8-908b-4b5a533bd6e8.png)

**Comment by Mu9tafa-Online** [comment]
@benhaynes / @rijkvanzanten  .. any updates on this ?!

**Comment by benhaynes** [comment]
No one here is able to reproduce this on the latest version. How did you install? Did you use the App installer, CLI, or schema.sql file? We're trying to figure out why your boilerplate schema would be different.

Could you give 7.0.2 a try with a fresh/blank database? We're pushing the migrations this Friday, but in the meantime the best way to test new versions is a fresh database install.

**Comment by Mu9tafa-Online** [comment]
Fine, I'm going to wait for the new version.

**Comment by christiaangoossens** [comment]
Whoops, didn't get notifications, but I had the same thing as @Mu9tafa-Online

**Comment by benhaynes** [comment]
Hey @christiaangoossens and @Mu9tafa-Online – just wanted to let you know that we figured this one out this morning. It was a problem with our default Apache `.htaccess` rules causing extensions to get intercepted by the API. Give it a try on the 7.0.4 release (coming out in a few minutes)

**Comment by Mu9tafa-Online** [comment]
Works fine now (v7.0.4) - Thaaanks guys :)
