### ISSUE TITLE
Field group start open not working

### ISSUE THREAD

**Issue by YannickMol** [directus/directus#7385]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When selecting the 'Start Open' option in the Interface section of the Field Group field, it actually doesn't start open. See below screenshots.

![image](https://user-images.githubusercontent.com/13256289/129262204-d5d9f1ba-5e9a-4dab-bbd5-ade83500ae34.png)
![image](https://user-images.githubusercontent.com/13256289/129262496-37ee0cb0-f717-4800-860a-64a265fce06e.png)

### To Reproduce

1. Create Field Group field with Interface 'Detail Group'.
2. In the Start field, select Start Open.
3. Go to the collection item and you will see that the field group doesn't start open. 

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

16.6.2

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by dwene** [comment]
I can confirm I'm having the same issue!

**Comment by rijkvanzanten** [comment]
https://github.com/directus/directus/blob/1b950b07dec6e41347da920d0dd6066e3dd5bf41/app/src/interfaces/group-detail/group-detail.vue#L10

This `start-open` should be on the `v-detail` further up in the file! Wanna open a PR @dwene?

**Comment by dwene** [comment]
Sure!

**Comment by dwene** [comment]
PR opened. https://github.com/directus/directus/pull/7411

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/7411

**Comment by pran01** [comment]
If the issue is solved, why is it still open?

**Comment by rijkvanzanten** [comment]
Because I forgot to hit close on my phone in the subway yesterday

**Comment by dreerr** [comment]
It seems this bug is back in 9.7.0, @YannickMol @dwene can you confirm?
