### ISSUE TITLE
Azure AD SSO is not working as expected

### ISSUE THREAD

**Issue by infomiho** [directus/directus#7653]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Trying to setup SSO with Azure AD doesn't work out of the box. I believe there are some bugs related to the redirect URLs. I'll try to provide as much info as possible, let me know if I can help in any way.

1. When you click on the button "Login with microsoft" you first go to `/auth/oauth/microsoft?redirect=https://domain.xyz/admin/login`
2. Then you are taken to the page `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&redirect_uri=https%3A%2F%2Fdomain.xyz%2Fauth%2Foauth%2Fmicrosoft%2Fcallback`

=> Which is wrong from the Microsoft's point of view and we actually put a different authorization URL in `.env`.
=> In the URL we have `common` as the tennant ID, but it should be `https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize?response_type=code&redirect_uri=https%3A%2F%2Fdomain.xyz%2Fauth%2Foauth%2Fmicrosoft%2Fcallback`

=> After changing the URL, other thing that Microsoft reports that `client_id` and `scope` are missing from the link, which would mean the link should have been actually `https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize?response_type=code&redirect_uri=https%3A%2F%2Fdomain.xyz%2Fauth%2Foauth%2Fmicrosoft%2Fcallback&client_id=<microsoft_application_id>&scope=openid email`

=> After manually adding the missing params and opening the right URL, we get redirected to Directus `/auth/oauth/microsoft/callback?code=XXX&session_state=XXX`

=> Which finally redirects me to the following error `/?error=Grant: missing session or misconfigured provider`

### To Reproduce

This is my current `.env`:
```
OAUTH_PROVIDERS="microsoft"
OAUTH_MICROSOFT_KEY="<microsoft_application_id>"
OAUTH_MICROSOFT_SECRET="<microsoft_application_secret>"
OAUTH_MICROSOFT_SCOPE="openid email"
OAUTH_MICROSOFT_AUTHORIZE_URL="https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize"
OAUTH_MICROSOFT_ACCESS_URL="https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token"

LOG_LEVEL="debug"

SESSION_STORE="database"

PUBLIC_URL="https://domain.xyz"
```

Some parts were redacted above:
- <tenant_id>
- <microsoft_application_id>
- <microsoft_application_secret>

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

v12.20.2

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker

**Comment by infomiho** [comment]
Long story short: I've forgot to forward some env variables in the `docket-compose.yml`. It works as expected now 👍

**Comment by youssef-ali** [comment]
> Long story short: I've forgot to forward some env variables in the `docket-compose.yml`. It works as expected now 👍

I have the same issue when run the app locally, please let me know how did you fix it?

**Comment by joselcvarela** [comment]
@youssef-ali probably you will need to configure your environment variables like this:
https://github.com/simov/grant-azure#configuration-1

Just prefix them with `OAUTH_` and make them uppercase.

**Comment by youssef-ali** [comment]
@joselcvarela Yes I configured them correct 
The issue is that directus send redirect_uri parameter with the PUBLIC_URL + /auth/oauth/microsoft/callback, and this appended part causes the problem of "AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application"

**Comment by joselcvarela** [comment]
Hey @youssef-ali 
The `PUBLIC_URL` is also passed via environment variables.
Can you check if that variable in your `.env` matches with the one you have configured on Azure?

**Comment by youssef-ali** [comment]
Hey @joselcvarela, yes it matches, but directus when redirects to login.microsoft, it pass `redirect_uri` in query strings with the `PUBLIC_URL` in .env and appended with "/auth/oauth/microsoft/callback".
I don't know why it appends this  part and is this the cause of the issue?

**Comment by joselcvarela** [comment]
Hey @youssef-ali 
I think I am not understanding the problem 🤔
Could you describe what are you expecting versus what is happening?

**Comment by rijkvanzanten** [comment]
> it pass redirect_uri in query strings with the PUBLIC_URL in .env and appended with "/auth/oauth/microsoft/callback".

That's the URL that the provider needs to redirect to on login, that path looks correct to me 👍🏻

**Comment by youssef-ali** [comment]
excuse me @joselcvarela,
expected that after login successfully the user will be redirected back to the configured PUBLIC_URL, but what happens that I get error "The reply URL specified in the request does not match the reply URLs configured for the application", I tried to set the PUBLIC_URL  with localhost, and with public domain and the same issue though they match the configured on the app on azure.

appreciate your support.

**Comment by joselcvarela** [comment]
Ooohh I think I understand now. Thank you @youssef-ali 
The `/auth/oauth/microsoft/callback` is necessarly to be appended to `PUBLIC_URL` because that route will handle the authentication in Directus. 
Have you tried to add the full URL in Azure? For example, if `PUBLIC_URL` is `https://directus-azure.com` then I think you will need to put `https://directus-azure.com/auth/oauth/microsoft/callback` in Azure

**Comment by rijkvanzanten** [comment]
> expected that after login successfully the user will be redirected back to the configured PUBLIC_URL

Not quite. It's the API that redirects back to the login page in the app, so the full flow is:

1) User clicks "login", app redirects to API (`/auth/oauth/:provider`)
2) API starts login session and redirects to the provider (azure.com)
3) On successful login, azure.com redirects to the API `/auth/oauth/:provider/callback`
4) API starts the Directus auth session, and redirects user back to the app (`PUBLIC_URL`)

**Comment by youssef-ali** [comment]
> Ooohh I think I understand now. Thank you @youssef-ali
> The `/auth/oauth/microsoft/callback` is necessarly to be appended to `PUBLIC_URL` because that route will handle the authentication in Directus.
> Have you tried to add the full URL in Azure? For example, if `PUBLIC_URL` is `https://directus-azure.com` then I think you will need to put `https://directus-azure.com/auth/oauth/microsoft/callback` in Azure

I tried that but the issue still exists

**Comment by youssef-ali** [comment]
@joselcvarela @rijkvanzanten 

Which application type should be on azure, Web or SPA? as I created new SPA and linked it but the same problem

**Comment by youssef-ali** [comment]
I made the same configuration before with angular application, and it worked smoothly :(

**Comment by youssef-ali** [comment]
Thanks @joselcvarela and @rijkvanzanten 
After some investigations I found that I have to add `http://localhost:4200/auth/oauth/microsoft/callback` at redirect url of the application on Azure, and add it to web platform not SPA. and making PUBLIC_URL="http://localhost:4200/"

Now there is another issue :) , azure redirect the user after login to `http://localhost:4200/admin/login?reason=INVALID_USER` and sometimes to `http://localhost:4200/admin/login?reason=SERVICE_UNAVAILABLE `

**Comment by joselcvarela** [comment]
You're welcome @youssef-ali 
I believe the `SERVICE_UNAVAILABLE` error comes from here:
https://github.com/directus/directus/blob/51148c11d6496b16a8be29860c6afa3ee4b942ba/api/src/utils/get-email-from-profile.ts#L18-L33

Since you are receiving `INVALID_USER` too, are you passing `OAUTH_MICROSOFT_SCOPE="openid email"` ?

**Comment by youssef-ali** [comment]
> Since you are receiving `INVALID_USER` too, are you passing `OAUTH_MICROSOFT_SCOPE="openid email"` ?

Hey @joselcvarela yes I'm passing `OAUTH_MICROSOFT_SCOPE="openid email"`, what is the problem?!

**Comment by joselcvarela** [comment]
@youssef-ali 
Can you open the developer tools while doing this flow?

Then check the Network tab and paste here the response of the error request.
Please be careful to obfuscate sensitive data.

**Comment by youssef-ali** [comment]
@joselcvarela 

All responses are 200 except on, `http://localhost:8055/auth/refresh` returns `400 Bad Request` with response body: `{"errors":[{"message":"\"refresh_token\" is required in either the JSON payload or Cookie","extensions":{"code":"INVALID_PAYLOAD"}}]}`

Also there is cookie  saved named `connect.sid`

**Comment by rijkvanzanten** [comment]
Any warnings in the api logs?

**Comment by youssef-ali** [comment]
> Any warnings in the api logs?
 
No warnings in the logs, just `Invalid user credentials` after `request completed GET 302 /auth/oauth/microsoft?redirect=http://localhost:8055/admin/login?reason=INVALID_USER`.

**Comment by joselcvarela** [comment]
@youssef-ali that could be a known issue already fixed here https://github.com/directus/directus/pull/8389/files and to be deployed on rc96
Are you using rc95? 
Some users reported that downgrading to rc94 could solve the problem: https://github.com/directus/directus/issues/8378

**Comment by infomiho** [comment]
If possible, please switch to a dedicated issue since this one is closed.

**Comment by youssef-ali** [comment]
Thanks @joselcvarela, please how can I install a specific version I tried  `npx create-directus-project@9.0.0-rc.94` and tried to install `npm i directus@9.0.0-rc.94` and also when create project I get `"directus": "^9.0.0-rc.95"`

**Comment by youssef-ali** [comment]
> Thanks @joselcvarela, please how can I install a specific version I tried `npx create-directus-project@9.0.0-rc.94` and tried to install `npm i directus@9.0.0-rc.94` and also when create project I get `"directus": "^9.0.0-rc.95"`

@joselcvarela  I updated the version in package.json to be  `"directus": "9.0.0-rc.94"`, then removed nodemodules and execute npm install command, then started the project but still have the same issue `Invalid_User`

**Comment by rijkvanzanten** [comment]
@youssef-ali when installing through NPM, you can use the `--save-exact` flag to prevent it from adding the `^` 👍🏻

**Comment by joselcvarela** [comment]
@youssef-ali it seems you are having trouble setting up, and not properly an issue.
Please use our discord chat [https//directus.chat]() to receive properly help

**Comment by youssef-ali** [comment]
Thanks all, after asking on Discord somebody told me that the user used to login on Microsoft should match user with the same email in directus. when I changed the email of admin created in installation the problem solved .

Thanks for your support.
