### ISSUE TITLE
Registration with password that doesn't match policy crashes server

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#8521]
### Preflight Checklist

- [x] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When a new user chooses a password that doesn't match a given password policy (I haven't actually set up one by myself, seems to be some default), the docker container exits with this error:

```
21:02:57 ✨ request completed POST 200 /users/invite/accept 13ms
/directus/node_modules/directus/dist/services/users.js:77
                    throw new exceptions_1.FailedValidationException({
                          ^

FailedValidationException [Error]: Provided password doesn't match password policy
    at UsersService.checkPasswordPolicy (/directus/node_modules/directus/dist/services/users.js:77:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsersService.updateMany (/directus/node_modules/directus/dist/services/users.js:160:13)
    at async UsersService.updateOne (/directus/node_modules/directus/dist/services/users.js:143:9) {
  status: 400,
  code: 'FAILED_VALIDATION',
  extensions: { field: 'password', type: 'regex', invalid: 'hahah$' }
}
```

Afterwards the server exits and has to be restarted manually.

### To Reproduce

Create new user account with this password: `hahah$`

### What version of Directus are you using?

9.0.0-rc.95

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Currently there shouldn't be any default password policy. Can you check these 2 places just so we can be extra sure your password policy isn't being set?

1. In the Project Settings page

    ![chrome_2foY4jctsH](https://user-images.githubusercontent.com/42867097/135794279-faee7724-6692-495b-9bef-569c65d3ae53.png)
   
2. In your database, specifically the `auth_password_policy` column in the `directus_settings` table

    ![chrome_0eM9qXy7NS](https://user-images.githubusercontent.com/42867097/135794300-c8c8255d-5f52-46eb-a64c-eab9292020e9.png)

If we look at the `checkPasswordPolicy` function, we can see that it will only check IF the column is not NULL:

  https://github.com/directus/directus/blob/afe7b15990e62fb8109469349071b79f2c69cde6/api/src/services/users.ts#L81-L101

---

I will be closing this ticket for now, but we can definitely reopen this if your `auth_password_policy` column is NULL yet the password policy is being triggered. In which case we might need your database dump to reproduce it 👍 hope that's understandable.

**Comment by azrikahar** [comment]
On hindsight, I just tested it by actually setting a password policy, and it does crash, so that shouldn't really happened in that regard. So I'll reopen this issue to address that. 

Do update us on your current setup as well, as Directus still shouldn't really have any default password policy out-of-the-box.

**Comment by aidenfoxx** [comment]
I can't reproduce this locally. Password policy is `NULL` by default and setting an actual password policy doesn't crash the server. I just get the following response trying to create a user:

```
{
  "errors": [
    {
      "message": "Provided password doesn't match password policy",
      "extensions": {
        "code": "FAILED_VALIDATION",
        "field": "password",
        "type": "regex",
        "invalid": "hahah$"
      }
    }
  ]
}
```

Even setting an invalid password policy doesn't crash the server: `Invalid regular expression: /[/: Unterminated character class` 🤔 

Maybe this has been fixed already? I'm running the latest version of `main`.

**Comment by LevinGermann** [comment]
> Do update us on your current setup as well, as Directus still shouldn't really have any default password policy out-of-the-box.

There was a mis-information from my side, we actually have set the password policy to "Weak", I just couldn't remember that anymore.. 🙈

**Comment by aidenfoxx** [comment]
@LevinGermann In that case it's correct that the server threw the error, since the PW didn't meet the requirement. But it certainly shouldn't have crashed the server! 😅

**Comment by azrikahar** [comment]
@aidenfoxx thank you for checking on this as well! It really helps alot.

May I know when you create/update user password, is it via the UI? I did test that and it seems to work, but I think it still crashes when it's done via the accept invite password page, at least it is for me. Would you mind trying the following:

https://github.com/directus/directus/blob/fb815913573cfff3e724f34bf5102fb85f84f1ac/api/src/services/users.ts#L266-L276

(unless you do have smtp setup locally, in which case feel free to ignore these first 2 steps)
- comment out this code since we can't send email locally 
- get `inviteURL.toString()` via console log /debugger
- open the URL in another browser/incognito and try to set an invalid password

It shows success on the UI, but crashes the API (you can try navigation around your admin window and it won't work). It'll be very helpful if you can verify this to avoid it being just a setup issue on OP/my end. 🙏

@LevinGermann glad it's not Directus gaining sentience haha. However the question still remains, your app still crashes right?

**Comment by LevinGermann** [comment]
@azrikahar I agree! 😉
I just checked again, and yes the issue persists. I invited a new email, went to the signup page, entered a password that doesn't match the policy and server still crashes/exits.

**Comment by azrikahar** [comment]
@LevinGermann Thanks for checking. Just to be sure of the whole behaviour, does the UI shows `Account Created Successfully` despite the server crashing in your setup?

![msedge_32Mk7DELU9](https://user-images.githubusercontent.com/42867097/135817574-f6f65279-a206-44fc-bc99-68e61cb309de.png)

**Comment by aidenfoxx** [comment]
@azrikahar I think the issue is that these lines aren't awaited

https://github.com/directus/directus/blob/fb815913573cfff3e724f34bf5102fb85f84f1ac/api/src/services/users.ts#L300
https://github.com/directus/directus/blob/fb815913573cfff3e724f34bf5102fb85f84f1ac/api/src/services/users.ts#L364

**Comment by azrikahar** [comment]
@aidenfoxx ahhh spot on! I totally didn't notice that.. 🤦‍♂️do you want to create a PR for it?

**Comment by aidenfoxx** [comment]
Sure. I can take it.
